### ISSUE TITLE
Setzen von Präferenzen durch das Frontend

### ISSUE THREAD

**Issue by FabianSig** [FabianSig/DHBW-ASWE-Personal-Digital-Agent#51]
Durch das Frontend sollen Präferenzen gesetzt werden können.

Momentan können der Wecker und Allergene gesetzt werden:

![image](https://github.com/user-attachments/assets/f57d744f-4215-447d-ad55-50dbdef0e06a)

![image](https://github.com/user-attachments/assets/2f032eb6-b332-417e-a0af-ecc380816b83)

**Comment by einBuegelbrett** [comment]
@A2i2C 

Ich übernehme das.

**Comment by einBuegelbrett** [comment]
Done with https://github.com/FabianSig/DHBW-ASWE-Personal-Digital-Agent/commit/750ca7c56641a6e58ea12c4b7ae827b0c9cce790
